### PR TITLE
Add original description on cascading MR

### LINKED ISSUE #27: Add original description on cascade MR
In our workflow, we always create an MR to solve a GitLab issue. Thus we're excepting that when MR is resolve that issue is automatically close if using [GitLab issue closing pattern](https://docs.gitlab.com/ee/administration/issue_closing_pattern.html)

The problem is that GitLab, only closing issue on default branch and GitLab could have only 1 default branch per repo.

In our case default branch is always latest version, here for example `3.0.0` (in following example, `3.0.0` is using meta/trunk branch `main` unlike `2.3.1` which is linked to `main/2.3.1`) . But if we've to fix on `2.3.1` we'll create a merge request on `main/2.3.1` with for example description containing 

```
fixes #XXX
```

and _ucascade_ will correctly create a merge request automatically but original description with `fixes #XXX` will not part of description of this newly created MR.

**I've already forked for our need but I'd like to know if is something that you're interested and thus I could propose a PR** (it could be configurable and disabled by default).

In our fork version MR will looks like (I've also done some _style_ update, like adding icon and emphasis)

Screenshot 2024-05-14 at 18 27 23

by default original description is using built-in `<summary>` tag to be fold, but if you can unfold you could see (here our description is complete, is just short description :) because in our workflow most of information already part of issue. Thus there is no filtering on original description).
And if you've multiple level of cascade, it will always take the original (starting point) description not n-1!

Screenshot 2024-05-14 at 18 27 29

And so at then end, on the issue link will be conserved/cascaded and as soon that ucascade MR will reach our default branch the issue will be automatically close (in case there is an issue closing pattern)

Screenshot 2024-05-14 at 18 41 28

### PR DESCRIPTION
**Pull request by kakawait**
Fixes #27 

Contains several things:

1. Cascading MR description
2. Add more style / emoji on cascade MR description
3. fix (possible?) bug on GitLab CE (on our side MR was not assigned when conflict, I was suspecting was related that GitLab CE only accept 1 assignee, multiple is for EE/Paid version)

Tests passed locally without changing it. I've tried to do not increase the number of GitLab API calls!

--

PS: Sorry some emergency not yet find to time to cleanup the git log. I'll try asap but I still propose in case of

### CODE REVIEW

**Comment by jmini** [comment]
Thank you for the PR. We will have a look ASAP.

> Sorry some emergency not yet find to time to cleanup the git log.

our policy is to squash the commits of a PR, so it doesn't matter for the history.

**Comment by jmini** [comment]
> fix (possible?) bug on GitLab CE (on our side MR was not assigned when conflict, I was suspecting was related that GitLab CE only accept 1 assignee, multiple is for EE/Paid version)

This is something where a config might be interesting.
We have the commercial version of GitLab where we can assign multiple assignee to one MR.

But when testing ucascade on gitlab.com where we only have a free account, we noticed that only one assignee was possible.
In that case it would make sense to keep only the assignee of the original MR.

And for users of the commercial version, keep it as it is today: add all assignees of the original MR + the merge-user to the ucascade MR.

**Comment by kakawait** [comment]
> > fix (possible?) bug on GitLab CE (on our side MR was not assigned when conflict, I was suspecting was related that GitLab CE only accept 1 assignee, multiple is for EE/Paid version)
> 
> This is something where a config might be interesting. We have the commercial version of GitLab where we can assign multiple assignee to one MR.
> 
> But when testing ucascade on gitlab.com where we only have a free account, we noticed that only one assignee was possible. In that case it would make sense to keep only the assignee of the original MR.
> 
> And for users of the commercial version, keep it as it is today: add all assignees of the original MR + the merge-user to the ucascade MR.

What I've did is:

If we're using GitLab CE, btw the number of assignee can't be more than 1 (so `if (cascadeResponsibleIds.size() > 1)` always false), thus I'm using `withAssigneeId` and even if you're on EE edition if you've assignee only 1 there is no reason that `withAssigneeId` can't work.
So I didn't need to check `CE` or `EE` version :)

**Comment by fbpe** [comment]
> If we're using GitLab CE, btw the number of assignee can't be more than 1 (so if (cascadeResponsibleIds.size() > 1) always false)

Even using Gitlab CE, the `cascadeResponsibleIds.size()` can be `> 1` at this point in the code. If the user that merged the original MR was not its assignee, we consider both the MR merger and the MR assignee as cascade responsibles. This is where we process this logic: https://github.com/unblu/ucascade/blob/a216a79183fa54b66856eaf9aeff9d0f73e5e89e/src/main/java/service/GitLabService.java#L551-L553

Nonetheless, I also agree that we can add the configuration to distinguish between Gitlab CE/EE in a follow-up Issue/PR.

For the scope of this PR, it looks good to me like this.

**Review by jmini — APPROVED** [review]

**Pull request merged**
